### ISSUE TITLE
Failed to save to database

### ISSUE THREAD

**Issue by TLado** [smartclash/Sandeadry#3]
I am working on Windows, with the latest go version and sqlite downloaded. The problem is this error: 

**←[0m←[31m[error] ←[0mfailed to initialize database, got error Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
Couldn't save the files into database Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub**

Previously I managed to scrape the site https://www.sanfoundry.com/cplusplus-interview-questions-answers/ with the warning: Couldn't load .env file (I don't know if this is important), but running "sandeadry save" gives me this error.

**Comment by smartclash** [comment]
If you just want to scrape and save data into sqlite, disregard the `env` file warning. If you want to save data into Meillisearch for indexing, you're expected to copy `.env.example` into `.env` file with appropriate values.

> ref: https://github.com/smartclash/Sandeadry#index-mcqs-to-meilisearch

For the issue with go-sqlite3 requiring cgo to work, it's highly system dependent. There are multiple workarounds to get this fixed. I recommend you to google `go-sqlite3 requires cgo to work.` and find your solution. 

This is not related to the project on it's own :)
